### ISSUE TITLE
Download options, full article pdf only for now

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#10]
## Problem / Motivation
 
- WHO Reader
- WHAT I would like to be able to download and copy of the full article
- WHEN & WHERE any time, in the article page (first load, after reading part of it, after coming back to it)
- WHY To read the article offline, index into a reference management system, to read on other devices

## Proposed solution

- Use the existing download icon. The icon does't need to open an overlay menu. It can trigger the download of the pdf like on podcast page
- We only need a link to download PDF full article link for now, no other links there

## Tasks

- [ ] Article schema must include a link or a reference that can be used to build a link
- [ ] Journal needs to render the download icon and menu

## Clarification needed and assumptions

- We will only store the latest article version PDF
> It would be the most recently supplied PDF
- The PDF asset location will be provided in the XML
> It won't be the absolute path. It's just file name in the XML.
- Follows: the article store will copy the PDF and substitute the link in the stored XML

## Technical notes
- Use `Content-Disposition: attachment; filename="elife-35692-v1.pdf"`
- Start with a persistent volume attached to the relevant article store container(s)? Limits only one container of that kind being created, doesn’t scale
- Start with a cloud provider specific solution and provide alternatives? Google Cloud Storage or S3 as default?

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/43402053-9e428918-9409-11e8-9da5-4aa99a098175.png)

**Comment by thewilkybarkid** [comment]
JATS to read:

```xml
<article-meta>
    <self-uri content-type="pdf" xlink:href="[something]"/>
</article>
```

taking `@xml:base` into account (must be an absolute URI).
