### ISSUE TITLE
Add superscript text

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#105]
Should be similar to https://github.com/libero/pattern-library/tree/master/source/_patterns/00-atoms/inline/italic.

- [x] Create pattern
- [x] Support `{http://jats.nlm.nih.gov}sup`

**Comment by discodavey** [comment]
https://github.com/libero/pattern-library/pull/50

**Comment by thewilkybarkid** [comment]
Not sure why this was closed?

**Comment by nlisgo** [comment]
Closed in error while attempting to adjust the description.

**Comment by davidcmoulton** [comment]
Closing manually as moving to "Done" wasn't enough due to it being from a different project.
