### ISSUE TITLE
Add subscript text

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#106]
Should be similar to https://github.com/libero/pattern-library/tree/master/source/_patterns/00-atoms/inline/italic.

- [x] Create pattern
- [x] Support `{http://jats.nlm.nih.gov}sub`

**Comment by discodavey** [comment]
https://github.com/libero/pattern-library/pull/51

**Comment by thewilkybarkid** [comment]
Not sure why this was closed?

**Comment by nlisgo** [comment]
I have no memory of closing it. I amended the description.
