### ISSUE TITLE
Return search errors in the Libero format

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#108]
- [ ] All errors conform to the [Libero error format](https://docs.google.com/document/d/1JhVpW8dxAuJqnk2YsQa76yxdIV_BlOd1QIi02fIu9mo/edit#heading=h.n8opb880a5)

**Comment by thewilkybarkid** [comment]
https://github.com/libero/api-problem-bundle is the equivalent PHP library.

**Comment by GiancarloFusiello** [comment]
@thewilkybarkid Do we have XML schema/schemas for errors?

**Comment by thewilkybarkid** [comment]
https://github.com/libero/schemas/blob/master/api/error.rng
