### ISSUE TITLE
Rewrite test for empty response using schema validation on search API

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/libero#111]
## Problem
The current tests for the search API are not checking responses against a schema. Testing/validating against a schema checks that the produced document is well formed and simplifies testing as tests can focus on specific checks rather than checking document structure also. 

## Proposed solution
- create a schema
- modify tests to validate responses against the new schema document

## Technical notes
Ideally, schemas should be central and brought into a project as a dependency but this should be a separate issue.

**Comment by thewilkybarkid** [comment]
> Ideally, schemas should be central and brought into a project as a dependency but this should be a separate issue.

Agreed, copy from https://github.com/libero/schemas/blob/master/api/content/item-list.rng for now.
