### ISSUE TITLE
Deploy Content Store to the unstable environment

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#117]
- [x] `scholarly-articles` Content Store is deployed 
  - [x] Has fixtures
- [x] `blog-articles` Content Store is deployed 
  - [x] Has fixtures

Depends on #116

**Comment by giorgiosironi** [comment]
Added `DOCKER_*` and `TRAVIS_*` (future use) environment variables to settings.

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/content-store had some credentials problems in pushing to Docker Hub however, solving that first.

**Comment by giorgiosironi** [comment]
First tag available at https://hub.docker.com/r/liberoadmin/content-store/tags

**Comment by giorgiosironi** [comment]
https://github.com/libero/sample-configuration/pull/17 is there, but also creating an empty group https://github.com/orgs/libero/teams/infrastructure-reviewers to be filled in.

**Comment by giorgiosironi** [comment]
Also https://github.com/libero/environments/pull/15 makes it easy to add `content-store` to the deployed applications.

**Comment by giorgiosironi** [comment]
Repeated the last deployment and checked health:
https://travis-ci.com/libero/environments

**Comment by giorgiosironi** [comment]
Same fixtures as what `dummy-api` was using are in place, with both `content-store`s now running and connected to `browser`.
