### ISSUE TITLE
Determine requirements for JavaScript in Gulp build pipeline

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#118]
We need a way to author, check, test, and build JavaScript in the pattern library.

- [x] document level of transpilation required (Caveats IE 11 and @babel/plugin-transform-runtime, both to be addressed in #119)
- [x] document level of mustard cutting we want to apply  (Caveat IE 11, to be addressed in #119)
- [x] document bundling decision
- [x] document test framework
- [x] document linting approach

### Level of transpilation required
- Use Babel 7 (dependencies `@babel/core`, `@babel/preset-env`)
- Opt in to core 3 (not enabled by default) with `corejs: 3,` (dependency `core-js`)
- Define transpilation for browsers using browserslist (https://github.com/browserslist/browserslist)
- Use a `.browserslistrc` file to enable easy changes
- For MVP, a reasonable browsers list is `last 2 versions or not dead and not IE<11` if IE 11 is to be supported, or `last 2 versions or not dead and not IE<=11` if not (see Note on IE 11 below)
- Only include polyfills that are actually needed by authored code with `useBuiltIns: "usage",` (dependency `@babel/polyfills`)
- Investigate using [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/en/babel-plugin-transform-runtime). As we bundle the files, the benefits of eliminated duplication are small, but as it prevents namespace pollution when using polyfills, it might be worth it: it keeps options open with respect to extension models, as we've not tied that down yet. Should run pipeline with and without it and see how much gzipped file size the net addition of the bundled runtime adds.

### Mustard cutting
In the progressively enhanced browser environment of Libero Publisher we want to stop Opera Mini, and (some or all, see Note on IE 11 below) IE versions from getting the JavaScript at all, as the code will not be polyfilled to take account of them (performance):
- To allow IE 11 to load the JavaScript but disallow it for older IE versions and Opera Mini, use
```
typeof window.document.createElement('div')).dataset === 'object'
```
(see https://caniuse.com/#search=dataset).

- To disallow all IE versions and Opera Mini from loading the JavaScript, use 
```
typeof window.document.createElement('div')).dataset === 'object' && !!CSS && typeof CSS.supports === 'function'
```
(see https://caniuse.com/#search=dataset and https://caniuse.com/#search=CSS.supports)

### Bundling
Discussions with a CDN provider have revealed that for low latency networks, a lot of JavaScript file unbundling is resulting in no improved performance over HTTP/2, and in some cases slightly reduced performance, compared a JavaScript file that remains bundled or is split into only a very few pieces.

For HTTP/2 delivery of Libero JavaScript, we want the file split to give us 3 files:
1. application bundle: may change often
1. library bundle: contains only library code that will change infrequently
1. logical properties fallback bundle (see #88) that will change infrequently

Numbers 1 and 2 are intended to only be served to clients who have cut the mustard for using JavaScript. Number 3 should be served to all clients.

https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-multiple-destination.md looks like a useful place to start for configuring Gulp tasks to achieve this.

### Note on IE 11
As we're building the pattern library applying progressive enhancement, the core content and functionality should be available without JavaScript. With this in mind, IE 11 support should be decided once the JavaScript pipeline is established, using eLife's JavaScript codebase as a proxy:
1. copy [eLife's JavaScript source](https://github.com/elifesciences/pattern-library/tree/develop/assets/js) into a local clone of this repo with the JavaScript build pipeline established
1. generate the application and library bundles once using the browserslist `last 2 versions or not dead and not IE<11`
1. gzip both bundles
1. sum the file sizes of the gzipped bundles
1. repeat for the browserslist `last 2 versions or not dead and not IE<=11` and compare the the bundle file sizes with the previous run.
1. Assuming the first set of bundles is larger, the difference is the amount of bytes every client will be sent in order to enable JavaScript for IE 11 users. If this is more than a few bytes, IE 11 should not be supported.

### Linting
(Documenting approach, not going into details of individual rules here.)
- use [`ESLint`](https://eslint.org/)
- configure with an `.eslintrc` file
- use AirBnB's config as the starting point, [`eslint-config-airbnb`](https://www.npmjs.com/package/eslint-config-airbnb), as they have a solid approach to this stuff. Individual rules may be added / overridden as required

### Testing
- test framework:  [`mocha`](https://mochajs.org/) via [`gulp-mocha`](https://www.npmjs.com/package/gulp-mocha). Not used in-house with Gulp 4 before so will need to make sure this will work okay (validate as part of #119.)
- assertion library: [`chai`](https://www.chaijs.com/)
- mocking library  [`sinon`](https://sinonjs.org/)

## Outstanding
To be addressed in #119.
- send JavaScript to IE 11?
- use `@babel/plugin-transform-runtime`?
- confirm `gulp-mocha` works with Gulp 4.

**Comment by davidcmoulton** [comment]
@thewilkybarkid @discodavey Do these decisions make sense to you?

**Comment by thewilkybarkid** [comment]
In some cases (eg #88) we do want to be able to support some JavaScript outside of this.

Do wonder if we can drop IE entirely...

/cc @stephenwf also

**Comment by discodavey** [comment]
According to IE the stats from March 1st 2018 - 2019 were 60 Users
<img width="635" alt="Screen Shot 2019-04-03 at 10 18 23" src="https://user-images.githubusercontent.com/745794/55467825-fbba0280-55f9-11e9-9461-82ed4c813d6d.png">

Also, what about users below 2g and less like we have done in eLife?

**Comment by discodavey** [comment]
The stats for IE are as follows:
<img width="518" alt="Screen Shot 2019-04-03 at 10 23 10" src="https://user-images.githubusercontent.com/745794/55468138-a7fbe900-55fa-11e9-8009-f01f87fe1a21.png">

with the breakdown of IE being this:
<img width="408" alt="Screen Shot 2019-04-03 at 10 24 04" src="https://user-images.githubusercontent.com/745794/55468171-b3e7ab00-55fa-11e9-9878-1036ef0009ff.png">

Also, are we doing what we did with JavaScript if the network connection drops below 2g and not serve it?

**Comment by davidcmoulton** [comment]
@thewilkybarkid Yes, #88 will have to be treated outside of the main js loading, as the non-js-targeted browsers, based on !browserlist, is orthogonal to supporting logical property fallbacks.

The point of providing a browserslist is to make the decision about what browsers to send js to part of the configuration. What that list actually is isn't necessarily so important at this stage, and will likely vary by publishers' target audience anyway. eLife on Libero may not want to send transpiled, polyfilled js to IE11, for example, but for another publisher somewhere else in the world it might make sense to.

**Comment by davidcmoulton** [comment]
@discodavey Not sure the network speed send-js / don't-send-js decision should be hard coded as it would depend on local context whether 2g speed is considered too slow to load js. Could make it part of the configuration though. Feel free to raise a ticket.

**Comment by thewilkybarkid** [comment]
> The point of providing a browserslist is to make the decision about what browsers to send js to part of the configuration. What that list actually is isn't necessarily so important at this stage, and will likely vary by publishers' target audience anyway. eLife on Libero may not want to send transpiled, polyfilled js to IE11, for example, but for another publisher somewhere else in the world it might make sense to.

I guess it's more what browsers does Libero JS support, so it's fine for an implementer to go stricter (but couldn't go more lax). Doesn't mean that any supplemental JS has to follow the same level.

**Comment by davidcmoulton** [comment]
If we weren't using Babel I'd definitely want to drop JavaScript support for IE 11 as long as the usage stats justified it, because of the paucity of its support for modern JavaScript features (https://kangax.github.io/compat-table/es6/#ie11).

This proposal is to use Babel 7 with core-js 3, which provides good support for many of the js features that IE11 lacks (see https://kangax.github.io/compat-table/es6/#babel7corejs3). If we code to what Babel 7 + core-js 3 supports (which is everything we're likely to want to do), then I don't think IE11 will be a problem. If it turns out that a particular behaviour uses a new DOM feature, then we'd have to screen out non-supporting browsers anyway (matches your comment about a higher bar when needed).

For me it comes down to performance. Is the transpiled js which caters to IE 11 significantly larger than the one that doesn't, and is it worth the bytes to all users for the IE11 users to get the full experience? As we don't have any js in Libero yet we can't say for sure, but I'll run some tests transpiling eLife's JavaScript codebase and see how it's looking.

**Comment by discodavey** [comment]
I agree with performance wise. If the file is that much bigger for IE11 users for full experience then I think we should just do graceful fallback for them so they can still use the site but not with bells and whistles.

**Comment by davidcmoulton** [comment]
Fleshed this out a lot. Gone into detail on how to address the IE 11 decision, and have added sections on bundling, testing and linting. #119 will be where the actual action happens.

Welcome your thoughts @thewilkybarkid @discodavey @stephenwf 

(Some form of this could make it into docs once it passes the validation of implementation of #119 and is shown to work.)

**Comment by thewilkybarkid** [comment]
👍 Seems like a well-thought out and sensible plan.

We might need to consider how libraries should be used. For eLife we didn't use many at all; we probably want to consider using them in favour of writing code, as long as usual standards apply (plus taking the resulting size into account).

**Comment by davidcmoulton** [comment]
How we could use libraries should become clearer with the `browserify` work in #119.

When we should use libraries is a judgement call. I'm generally in favour of using a library if the benefit it provides in terms of rigour and convenience justifies the extra byes. This means investigation and testing rather than just install and forget. "justifies" is doing a lot of work here, but because of the way we review PRs I'm confident we'll find a workable approach.
