### ISSUE TITLE
Organise content into sections

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#12]
## Problem / Motivation
 
- WHO readers
- WHEN skimming through an article or reading it
- WHAT understand the structure of the article
- WHY find and access the content of an article more quickly

## Proposed solution
- Top-level sections such as Introduction, Results, Discussion are located ~in accordions~ like on elife's journal (see screenshot below)
- The nested sections names are pulled from the XML

## Tasks

- [x] Add pattern (https://github.com/libero/pattern-library/pull/55)
- [x] Support `{http://jats.nlm.nih.gov}sec` when there's a `{http://jats.nlm.nih.gov}title`. (https://github.com/libero/browser/pull/41)

## Assumptions
- Only the Introduction section is opened by default when landing on an article
- The abstract section is located in an accordion and is always visible to the users
- eLife & Hindawi: Top-level sections are coming from a list of pre-defined sections

## Clarification needed

- What is the list of pre-defined top-level sections? Is the same one as eLife?
> IJM do not have a standard structure, but all articles have numbered sections (generally: Introduction, Literature, Model, Data, Results, Conclusions, or variations thereof).
- RSC requires a flexible list of Top-level sections. Does it need to be pre-defined? Can we pull the sections from the XML? 

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/43574942-609a1a28-963d-11e8-8bf7-39fcf2efbc50.png)

**Comment by thewilkybarkid** [comment]
The opening/closer behaviour will need to be a follow-up ticket. The initial build will just be the non-JS version.
