### ISSUE TITLE
Create JATS-support schema

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#121]
## Problem / Motivation

We're going to 'support' JATS, but it will only ever be a subset. It's currently unclear _what_ JATS we will support. (It's still possible to write code to add support for other variants.)

## Proposed solution

Create a schema (Schematron?) that indicates what parts of a JATS article will supported. To start with this should fail pretty much everything. As we agree to support more things then we'll relax it.

**Comment by thewilkybarkid** [comment]
Created https://github.com/libero/jats-support.

**Comment by thewilkybarkid** [comment]
And first support added in https://github.com/libero/jats-support/pull/1.

**Comment by Melissa37** [comment]
@thewilkybarkid This is a fantastic idea and I really like it!
Look forward to seeing this progress.

**Comment by thewilkybarkid** [comment]
Opened https://github.com/libero/jats-support/pull/2, https://github.com/libero/jats-support/pull/3, https://github.com/libero/jats-support/pull/4 and https://github.com/libero/jats-support/pull/5 add in what we currently support, just `<subj-group subj-group-type="heading">` to go.
