### ISSUE TITLE
Incorrect selector specificity for logical properties causes fallbacks to take priority

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#124]
Incorrect CSS selector specificity is causing the logical property fallbacks to override the main implementation when an element lacks the `dir` attribute.

The fix looks simple and will include updating some tests.

 # Location
 `all.css`. (As this is compiled code line numbers are subject to change so won't be used to refer to the contents of this file.)

 # Characterisation
 In the following snippet from `all.css`, `margin-left` or `margin-right` will be applied in preference to `margin-inline-start`, even in browsers that support logical properties, because the selector specificity of `html[dir] dd` is lower than `html[dir="ltr"] dd:not([dir])` and `html[dir="rtl"] dd:not([dir])`.

 ```
 html[dir="ltr"] dd:not([dir]), dd[dir="ltr"] {
   margin-left: 0; }

 html[dir="rtl"] dd:not([dir]), dd[dir="rtl"] {
   margin-right: 0; }

 html[dir] dd {
   margin-inline-start: 0; }
 ```

# Steps to reproduce
1. Open the following specimen HTML in a logical-property-supporting browser. It sets a border on one side of each element: a red border is set using physical properties, a green border is set using logical properties. The expected behaviour is that all borders set will be green.
1. Observe that the border on the element without a `dir` attribute is red, and so is being set with physical properties rather than logical properties.
1. Change `<html dir="ltr"...` to `<html dir="rl"` and observe the same effect.

Specimen HTML showing bug:
```
<!doctype html>
<html dir="ltr" lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <style>

    html[dir="ltr"] .test:not([dir]),
    .test[dir="ltr"] {
      border-left: 10px solid red;
    }

    html[dir="rtl"] .test:not([dir]),
    .test[dir="rtl"] {
      border-right: 10px solid red;
    }

    html[dir] .test {
      border-inline-start: 10px solid green;
    }

  </style>
</head>

<body>

<div class="test">No dir attribute on this element</div>
<div class="test" dir="ltr">This element has dir=ltr</div>
<div class="test" dir="rtl">This element has dir=rtl</div>

</body>
</html>


```

# Proposed fix
Address in [_logical-properties.scss](https://github.com/libero/pattern-library/blob/master/source/css/sass/mixins/_logical-properties.scss#L19), changing the selector on line 19 to:

```
html[dir] &:not([dir]),
html[dir] &:[dir],
```

Changing the specimen HTML from above to the following demonstrates how this would work:

```
<!doctype html>
<html dir="rtl" lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <style>

    html[dir="ltr"] .test:not([dir]),
    .test[dir="ltr"] {
      border-left: 10px solid red;
    }

    html[dir="rtl"] .test:not([dir]),
    .test[dir="rtl"] {
      border-right: 10px solid red;
    }

    html[dir] .test[dir],
    html[dir] .test:not([dir]) {
      border-inline-start: 10px solid green;
    }

  </style>
</head>

<body>

<div class="test">No dir attribute on this element</div>
<div class="test" dir="ltr">This element has dir=ltr</div>
<div class="test" dir="rtl">This element has dir=rtl</div>

</body>
</html>
```

Repeating the documented steps to reproduce with this specimen HTML shows the bug is fixed.

**Comment by thewilkybarkid** [comment]
Hello specificity, my old friend.

**Comment by thewilkybarkid** [comment]
https://codepen.io/thewilkybarkid/pen/LarjzG

`html[dir][dir] .test` also works.

**Comment by discodavey** [comment]
https://github.com/libero/pattern-library/pull/74
