### ISSUE TITLE
Keywords and Tags, Research organism

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#13]
## Problem / Motivation
 
- WHO wants this?
- WHEN when I look at the bottom of the article
- WHAT to be able to see the keywords associated with an article
- WHY so that I can easily access related articles

## Proposed solution

- The first part titled "CATEGORIES AND TAGS" will contain the following: keywords, article subject area and article type
- The other parts will depend on the journal disciplines, for example, RESEARCH ORGANISMS for life science journals and IJM for economics journals. (see related ticket #9)  
- eLife's journal design pattern will be reused

## Tasks

- [ ] TBC

## Clarification needed and assumptions

- Is the header “Categories and tags” generic enough and suitable for other journals?
> Hindawi and RSC doesn't use keywords

## Assumptions
- The RESEARCH ORGANISMS section won't appear in this section if this isn't relevant for the article
- The keywords in the XML are manually entered by authors during the submission process

## Technical notes
- The author keywords in the XML: `kwd-group-type="author-keywords"`

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/43579317-891313f4-9649-11e8-9680-418419cd3064.png)

**Comment by thewilkybarkid** [comment]
Requires https://github.com/libero/libero/issues/99 before can be used in Browser.

**Comment by thewilkybarkid** [comment]
Having a basic approach working in Browser, waiting for the existing PRs there to close before opening.

**Comment by thewilkybarkid** [comment]
> * The first part titled "CATEGORIES AND TAGS" will contain the following: keywords, article subject area and article type

Can we drop this @Maelplaine? Seems quite opinionated and unclear where the information for these exists outside of eLife-style JATS (eg the JATS documentation refers to `<kwd-group kwd-group-type="author">` whereas we use `<kwd-group kwd-group-type="author">`).

> * The other parts will depend on the journal disciplines, for example, RESEARCH ORGANISMS for life science journals and IJM for economics journals. (see related ticket #9)

My proposal for this is to display all the `<kwd-group>`s with a `@kwd-group-type` and/or `<title>`. So an eLife article would get 'Author keywords, Research organism'. An IJM article 'Author keywords, JEL classification'.

Means that subjects and article types aren't shown here (but are elsewhere on the page). We can always override it later to implement the current eLife style for eLife/IJM.

**Comment by Maelplaine** [comment]
Yes Chris that's a good idea and that makes sense
