### ISSUE TITLE
Style images

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#135]
Style the image (with title and caption):

<img width="662" alt="Screenshot 2019-04-09 at 13 20 59" src="https://user-images.githubusercontent.com/1784740/55799953-75eef900-5aca-11e9-81a9-b4fa6bb9fdba.png">

## Tasks

- [x] Styles added
  - [x] Image
  - [x] Title
  - [x] Caption
- [x] Deployed in Browser

## Related

- Blocked by #129.

**Comment by davidcmoulton** [comment]
PR into browser to satisfy final item in check list ready for review at https://github.com/libero/browser/pull/82/files
