### ISSUE TITLE
Add download icon to content header

### ISSUE THREAD

**Issue by discodavey** [libero/libero#150]
Add a link to download 

<img width="121" alt="Screenshot 2019-05-06 at 15 08 54" src="https://user-images.githubusercontent.com/1784740/57230775-07da1b00-7011-11e9-8307-aa0a6a0e7b6b.png">

## Tasks

- [ ] Add download icon to the content header pattern.

Related to: https://github.com/libero/libero/issues/144

**Comment by discodavey** [comment]
https://github.com/libero/pattern-library/pull/98

**Comment by davidcmoulton** [comment]
Closing in favour of #144. We're not splitting out pattern-library work from other required work for features.
