### ISSUE TITLE
Avoid setting padding, margin & inset shorthand as they use physical properties

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#152]
### Description
When using `padding` or `margin` (or `inset` when it arrives) shorthand syntax, the underlying properties set are physical, not logical. This becomes significant if different values are set at opposite ends of the same axis. It is incorrect for Libero to use this approach: Libero should be using logical properties throughout, even implicitly. This behaviour of the shorthand syntax, using the inline axis as the example, has been characterised for [padding](https://codepen.io/davidcmoulton/pen/yWvMZm) and [margin](https://codepen.io/davidcmoulton/pen/eaMvwO).

### Action
The `padding()`, `margin()` and `inset()` mixins should be changed to explicitly use logical properties (with fallbacks) when different values are set for different ends of the same axis in these situations, for (non-exclusive) example:
- https://github.com/libero/pattern-library/blob/master/test/sass/mixins/spacing.spec.scss#L283
- https://github.com/libero/pattern-library/blob/master/test/sass/mixins/spacing.spec.scss#L1449

Only applies to the `inline` axis at the moment as we've not yet fully implemented logical properties for vertical writing modes.

**Comment by thewilkybarkid** [comment]
It should be fine when the values are the same, eg https://github.com/libero/pattern-library/blob/4e5a8987a9ee9ea777f3eb32d2c737ea2ba57cfe/test/sass/mixins/spacing.spec.scss#L330. (Though the redundant values should be removed.)

**Comment by davidcmoulton** [comment]
Can probably be safely ignored for block-axis for now, as we've not fully implemented logical properties for vertical writing modes yet.

**Comment by davidcmoulton** [comment]
PR for review at https://github.com/libero/pattern-library/pull/106
