### ISSUE TITLE
Investigate impact of using hypermedia rather than strict API service specifications

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#153]
The current Libero API spec has a concept of services (https://docs.google.com/document/d/1JhVpW8dxAuJqnk2YsQa76yxdIV_BlOd1QIi02fIu9mo/edit#heading=h.ule1npii5d5y) that is quite rigid (this is based on the structure of the current eLife API).

Linked data (JSON-LD) was investigated and rejected for its complexity, but the basics of hypermedia might still be beneficial in terms of flexibility and longevity.

**Comment by thewilkybarkid** [comment]
Created https://github.com/elifesciences/libero-html-hypermedia-experiment. Needs more thought, but initial feeling is that, despite some promising features, this would be a step too far to actually adopt.

**Comment by thewilkybarkid** [comment]
Other option I want to look at is Hydra. I did investigate JSON-LD early in the process, but that was more in regards to representing _everything_ that way (and the document parts really don't work).

**Comment by thewilkybarkid** [comment]
Hydra has turned out to be quite frustrating. It appears to be great (and the right answer), but the documentation and tooling is pretty much non-existant. As far as I can tell, it's not used that much either (probably for those reasons).

JSON-LD is sound (as is Schema.org). Might be able to use that though; might mean custom hypermedia (or not at all).

**Comment by giorgiosironi** [comment]
First point: is the ship for HTML 5 APIs sailed? I've worked with `Link` headers some time in the past, but never encountered a production API based on HTML responses.

I've seen recent efforts in this direction going for:
- [JSON:API](https://jsonapi.org/) though [HTTP/2 may make some parts of it obsolete](https://apisyouwonthate.com/blog/lets-stop-building-apis-around-a-network-hack)
- more on the bleeding edge [JSON Hyperschema](https://apisyouwonthate.com/blog/getting-started-with-json-hyper-schema), trying to extend JSON Schema with links.

Common example of where hypermedia shines: 
- complex state machines on the server side: we have flags enabling/disabling parts of a document but I can't think of many actions that are available, given it's a read-heavy API?
- multiple clients not wanting to replicate logic: but we are only planning one client being in use over the API at a time in any specific distribution of Libero?
- related to the previous one: clients with needs for backward compatibility and public API evolution. Possibly of interest for backward compatibility, less for deployed clients e.g. a smartphone application that can't be modified and need to remain compatible.

**Comment by thewilkybarkid** [comment]
> is the ship for HTML 5 APIs sailed?

No. I quite like it, given it's a very well-known and stable technology (and can still make use of Schema.org vocabularies through microdata/RDFa Lite). Only real obvious problem is the lack of other HTTP methods in forms (eg no native `DELETE`), but a `_method` input is pretty standard.

> I've seen recent efforts in this direction going for:
> 
> * [JSON:API](https://jsonapi.org/) though [HTTP/2 may make some parts of it obsolete](https://apisyouwonthate.com/blog/lets-stop-building-apis-around-a-network-hack)
> * more on the bleeding edge [JSON Hyperschema](https://apisyouwonthate.com/blog/getting-started-with-json-hyper-schema), trying to extend JSON Schema with links.
> 
> Common example of where hypermedia shines:
> 

> * complex state machines on the server side: we have flags enabling/disabling parts of a document but I can't think of many actions that are available, given it's a read-heavy API?

Mostly CRUD, but articles may have a bit more state (approval, publication).

> * multiple clients not wanting to replicate logic: but we are only planning one client being in use over the API at a time in any specific distribution of Libero?

Multiple services reading it, so definitely multiple clients.

We have been working on the idea that the API would normally be internal rather than public, but having a public API would be a good selling point. (_Especially_ if it uses hypermedia/linked data) /cc @BlueReZZ

> * related to the previous one: clients with needs for backward compatibility and public API evolution. Possibly of interest for backward compatibility, less for deployed clients e.g. a smartphone application that can't be modified and need to remain compatible.

Easier to do when you have control of the clients, but change does need to be controlled still (even if the window between the API changing and the client being updated is small).

**Comment by giorgiosironi** [comment]
> Multiple services reading it, so definitely multiple clients.

Yes, I was probably thinking in terms of backends (plenty) vs. more disparate, external stuff like data pipelines/warehouses, smartphone applications, etc.

**Comment by thewilkybarkid** [comment]
Found that the in-GMail actions for emails are done through a `actionHandler` property on Schema.org actions. However, this isn't official. Searching for it suggests it was discussed when actions were originally proposed, but then disappeared. Will ask about it.

This might replace one of the main cases for using Hydra, and looks like it could be mapped to HTML forms. But might also be too limiting, will have an investigation.

**Comment by thewilkybarkid** [comment]
Added a new branch (https://github.com/elifesciences/libero-html-hypermedia-experiment/tree/rdfa) using RDFa, Schema.org and Gmail's action handler syntax. Works quite nicely, don't need to know about the HTML at all. Bit concerned about the quality of the PHP library though.

**Comment by thewilkybarkid** [comment]
Mind’s wondering a bit: wonder if we should actually be converting JATS or whatever to Schema.org/HTML. Could be done by a content store or a separate service. Means it’s easier to consume by Search, Browser or whatever, but can still be extended when needed.

Not entirely sure what body content would look like, there are vocabularies for it, but that’s a little crazy. Probably purely HTML (but has to be some convention on the things that HTML doesn’t natively cover). Makes things like IIIF pretty slick though since that’s already linked data...

**Comment by giorgiosironi** [comment]
While I go through the code, pointing out there are several layers to this:
- an XML API using multiple namespaces and custom schemas vs. an hypermedia API linking together various resources
- inside the second scenario, the possible formats for an hypermedia API from HAL (serialized in XML or JSON) to HTML

**Comment by stephenwf** [comment]
@thewilkybarkid I pulled down your hypermedia experiment, using HTML is an interesting idea, although from an API consumer standpoint, implementing an HTML to JSON-like structure and then back to HTML (for a browser), could be quite challenging and may not scale well. 

If I understand correctly, this format for hypermedia is as you say @giorgiosironi for linking together various resources in a standard way so multiple services returning responses can be understood uniformly, allowing clients to implement individual features of a response, opposed to implementing each response individually, with the idea being after a certain point clients will understand completely new responses without having to re-implement.

Leaning on something like Schema.org or other similar vocabulary for linked data makes sense, with well defined terms to build up the semantics of the API. 

Have you considered straight up RDF, pulling in Schema.org and building up a schema. This would allow for both an XML API but also would not be closing the door on JSON-LD, which could be still implemented as a serialisation. Could even use some terms from Hydra vocab, but keep a custom, more rigid subset to begin with. 

I understand that there might be complex use-cases, but I think HTML will run into similar problems. There's no conditionality in HTML, so you could not have a form where either one field can be populated or the other. It also doesn't have inherent linking. So you can't assign an input type to be a document that implements X schema (at least I don't think so with RDFa), and you may end up with more `<meta />` tags than semantic HTML. 

Also, if you did use RDF as the base, you could quite easily build new serialisations (RDFa, Hyperschema, JSON-LD, GraphQL/Relay) based on the underlying triples.

**Comment by GiancarloFusiello** [comment]
There appears to be many options. I always find to help make a decision it's useful to further define the problem.

What are the issues with the current API spec? What makes it rigid? (I realise these might be obvious but collecting a list of issues might prove beneficial or provide a specification when choosing a replacement).

**Comment by thewilkybarkid** [comment]
We've agreed that this will become an RFC, hopefully reasonably soon.

Ignoring possible formats for now, just thinking about hypermedia generally (ideally combined with using existing ontologies/vocabularies).

Main problems that I can currently see:

- A lot of the specs have to mostly be `SHOULD` or `MAY` (to allow for different implementations, eg a read-only version). This is hard to write reusable clients etc as there's no way to know what's possible without configuration.
- Most of the expected API is pretty straightforward (basic CRUD), but it seems that some areas need something more than what eLife had (eg an approval/publication workflow). Again this means having to use configuration, and is complicated to extend.
- Actions (eg publish) are currently due to just be a `PUT` (maybe `PATCH` if supported) that updates the item.
- It's XML focused, so won't support blog posts in Markdown etc.
- Not being able to have a canonical representation of documents and their metadata complicated matters downstream (eg Browser, Search having to understand JATS as well as other possibly other formats).
- A lot of existing specs are used, but there are still areas where new things are having to be invented (eg content API spec, XML schemas).

**Comment by thewilkybarkid** [comment]
This is an ugly (probably incomplete, possible wrong) braindump, but tried to imagine how the article creation and asset handling flow that's currently being developed would work (through the eyes of services interacting with the API), based on Schema.org types (which would be subclasses, ignoring for now), without thinking of the actual hypermedia format (think this could work natively with Hydra and HTML?).

1. JATS Ingestor goes to the [`EntryPoint`](https://schema.org/EntryPoint).
2. JATS Ingestor finds the [`FindAction`](https://schema.org/FindAction) for articles ([`ScholarlyArticle`](https://schema.org/ScholarlyArticle)).
3. JATS Ingestor performs the `FindAction` with no result.
4. JATS Ingestor finds the [`CreateAction`](https://schema.org/CreateAction) for a `ScholarlyArticle`.
5. JATS Ingestor performs the `CreateAction` (which contains little information, maybe even just a title?)
6. JATS Ingestor finds the `CreateAction` for a [`ImageObject`](https://schema.org/ImageObject) (or some other media type).
7. JATS Ingestor performs the `CreateAction` (which contains some information and the original format, eg TIFF, as an [`encoding`](https://schema.org/encoding)) for each asset.
    1. Image Converter follows the `ImageObject` link (present in the event) and finds current format.
    2. Image Converter downloads the current format.
    3. Image Converter converts to whatever formats/sizes are needed.
    4. Image Converter finds the [`UpdateAction`](https://schema.org/UpdateAction) for adding a new `encoding` to the `ImageObject`.
    5. Image Converter performs the `UpdateAction` to add each new `encoding`.
8. JATS Ingestor updates the JATS XML locally so assets reference the hosted assets.
9. JATS Ingestor finds the `UpdateAction` for adding a new `encoding` to the `ScholarlyArticle`.
10. JATS Ingestor performs the `UpdateAction` to add the JATS XML as an [`MediaObject`](https://schema.org/MediaObject) `encoding`.
    1. JATS Converter follows the JATS `MediaObject` link (present in the event).
    2. JATS Converter downloads the JATS.
    3. JATS Converter finds various actions for information attached to the `ScholarlyArticle` (eg updating the title, adding authors, citations, adding a HTML-based version of the main content which has links to the various assets).
    4. JATS Converter performs the various actions.
11. _Somehow_ processing is recognised as complete, and the status of the `ScholarlyArticle` is set to 'ready for review/preview'
12.
    1. Browser can now access it through the API and read the HTML-based content.
    2. Dashboard can now see actions that can be performed.

Initial thoughts:
- Definitely more moving parts, with chances to go wrong.
- Not having to read a variety formats like JATS in Browser, Search etc would make these services a _lot_ simpler.
- Chatty API, but don't think that in itself is a problem.
- Adds a lot of flexibility; gives more chance of applications being used out of the box (custom tasks are replaced with separate services).
- Fine-grained actions rather than generic `PUT`/`PATCH` operations feels a lot nicer (and access can be controlled tightly).
- Choreography has the problem of knowing when things are finished (maybe its actually a question of validation, eg constraints like each image must have a JPEG encoding?).
- An implementation detail, but not sure if the JATS Ingestor or JATS Converter should create the `MediaObject`s (if the latter, needs to be able to access them).

**Comment by thewilkybarkid** [comment]
Was just trying to find out more about the `actionHandler` property on Schema.org actions, and discovered that https://schema.org/Action doesn't quite give the full picture on what is possible, it's hidden away inside https://www.w3.org/wiki/images/1/10/PotentialActionsApril11.pdf (specifically part 4). Refs https://github.com/schemaorg/schemaorg/issues/1627.

This might well make Hydra unnecessary, will experiment.

**Comment by thewilkybarkid** [comment]
Pushed new experiment: https://github.com/elifesciences/libero-html-hypermedia-experiment/tree/schema.org

This is using the final Schema.org types, and has switched to JSON-LD (probably more realistic).

Seems to work (using `Action` with a `target` that's either a URI or an `EntryPoint`). Have only tried pretty simple examples though.

Immediate thoughts are:
- Going to need good tooling to make this a lot easier. (Which doesn't exist AFAIK.)
- Performance is a little concerning due to multiple requests and JSON-LD context resolution.

**Comment by thewilkybarkid** [comment]
Closing this. Next up is discussing it.
