### ISSUE TITLE
Deploy jats-ingester into the unstable environment

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#154]
* [x] push a production-oriented Docker image
  - [x] add credentials to Travis CI build
  - [x] verify health checks (2 out of 3 can be used)
* [x] add services to `sample-configuration`
  - [x] `postgres`
  - [x] `airflow_initdb`
  - [x] `airflow_webserver`
  - [ ] ~`airflow_nginx`?~
  - [x] `airflow_scheduler`
  - [x] `airflow_worker`
  - [ ] ~extensions to S3 Fake service if necessary~

**Comment by giorgiosironi** [comment]
Does this depend on the rename? Would be helpful not to have to rename published Docker images afterwards.

**Comment by giorgiosironi** [comment]
PR ready for review, but complete testing will only be possible in the real `unstable` environment.

**Comment by giorgiosironi** [comment]
Long story short, XML ingestion [works](http://unstable.libero.pub/articles/00666) but the base attribute for the ingestion of figures needs to be sorted out instead.

**Comment by GiancarloFusiello** [comment]
> Long story short, XML ingestion [works](http://unstable.libero.pub/articles/00666) but the base attribute for the ingestion of figures needs to be sorted out instead.

Technically, this is deployed correctly so, in my opinion, should be closed. I can open a separate issue for the article issue. Agreed?

**Comment by GiancarloFusiello** [comment]
I've opened a separate ticket: https://github.com/libero/libero/issues/173

**Comment by giorgiosironi** [comment]
> Technically, this is deployed correctly

Yes, the containers are running and the healthchecks are positive. I'll add a trigger between the build of the project and the `environments` deployment to facilitate the propagation of changes, then we can close.

**Comment by giorgiosironi** [comment]
Build [was triggered](https://travis-ci.com/libero/environments/builds/115396321) successfully. It did fail, but due to `elasticsearch` problems.

**Comment by giorgiosironi** [comment]
```
ubuntu@ip-172-31-70-78:~/sample-configuration$ docker inspect sample-configuration_search_elasticsearch_1 | jq .[0].State.Health
{
  "Status": "unhealthy",
  "FailingStreak": 8,
  "Log": [
    {
      "Start": "2019-06-13T09:53:46.554421341Z",
      "End": "2019-06-13T09:54:16.554602086Z",
      "ExitCode": -1,
      "Output": "Health check exceeded timeout (30s)"
    },
    {
      "Start": "2019-06-13T09:54:46.568375465Z",
      "End": "2019-06-13T09:55:16.568587033Z",
      "ExitCode": -1,
      "Output": "Health check exceeded timeout (30s)"
    },
    {
      "Start": "2019-06-13T09:55:46.586197356Z",
      "End": "2019-06-13T09:56:16.58639575Z",
      "ExitCode": -1,
      "Output": "Health check exceeded timeout (30s)"
    },
    {
      "Start": "2019-06-13T09:56:46.599614423Z",
      "End": "2019-06-13T09:57:16.599834256Z",
      "ExitCode": -1,
      "Output": "Health check exceeded timeout (30s)"
    },
    {
      "Start": "2019-06-13T09:57:46.614164942Z",
      "End": "2019-06-13T09:58:16.614381972Z",
      "ExitCode": -1,
      "Output": "Health check exceeded timeout (30s)"
    }
  ]
}
```

**Comment by giorgiosironi** [comment]
```
[2019-06-13T09:59:01,192][INFO ][o.e.c.r.a.DiskThresholdMonitor] [IU7dhop] low disk watermark [85%] exceeded on [IU7dhopCSJGk331TSYLttg][IU7dhop][/usr/share/elasticsearch/data/nodes/0] free: 990.8mb[12.5%], replicas will not be assigned to this node
```
We're gonna need a bigger boat.

**Comment by giorgiosironi** [comment]
Dealing with `search` issues separately.

**Comment by giorgiosironi** [comment]
There's a missing piece: the `environments` repository is missing this in its list.

**Comment by giorgiosironi** [comment]
Victory: http://unstable.libero.pub/articles/00666 has the figure.
