### ISSUE TITLE
Move config to sass and export to js / template where necessary

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#157]
## Problem / Motivation
The current approach to config generation is trying to solve two orthogonal problems:
1. allowing properties that need to be shared between sass / js / templates still to be managed in one place
1. eliminating magic numbers in the source

It was conceived to solve the first problem, but as it stands it needs also to be used to solve the second problem too. This is starting to cause the config file to grow, and it will soon become large, with the maintenance issues that brings; it also introduces an unnecessary layer of complexity when writing sass that does not contain any exportable values.

## Proposed solution
As (currently) all the values seem to be present in sass, the sass layer should be the definitive source of truth for these values and the values exported from sass to js / templating as required. 

[Initial investigation](https://github.com/libero/pattern-library/pull/104) by @thewilkybarkid shows this to be a viable approach.

## Tasks
Using the [initial investigation](https://github.com/libero/pattern-library/pull/104) as a jumping off point:
- [x] move all config values to sass, keeping them modular
~- [ ] use gulp to export to js / tempates as required~

## Clarification needed and assumptions
- This approach assumes that no values need to be shared between js and templates, but not sass. Should this arise, we'll need to decide on the best approach, but as things stand at the moment this seems unlikely

- This does not prevent sharing values to other parts of the libero technology stack, but it does mean that they need to be defined in Libero Publisher's sass, and exported from there

## Technical notes
The Gulp file is already quite complex and this adds to it further. Keep in mind the possibility of extracting the config export functionality into a library. This will keep the file simpler, and will make the technique available to the community more easily, independent of Libero Publisher.

**Comment by thewilkybarkid** [comment]
Using it in Twig is blocked by https://github.com/libero/libero/issues/190.

**Comment by thewilkybarkid** [comment]
Splitting exporting due to #190.
