### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#16]
## Problem / Motivation

- WHO the publisher
- WHEN on the page
- WHAT a menu
- WHY to try and get people to look at more pages

## Proposed solution

- Have a menu

## Tasks

- [ ] Create menu pattern
- [ ] Add menu pattern to page

## Clarification needed and assumptions

- Links can be internal or external

## Technical notes

- No JavaScript
- Needs visually-hidden descriptive text with the icon
- Needs a 'back to top' link

## User interface / Wireframes

Link on global navigation:
<img width="152" alt="screen shot 2018-08-07 at 14 37 17" src="https://user-images.githubusercontent.com/1784740/43779123-70be32de-9a4f-11e8-881e-d1df71bf1fe6.png">

Goes to:
<img width="392" alt="screen shot 2018-08-07 at 14 37 11" src="https://user-images.githubusercontent.com/1784740/43779125-7203688a-9a4f-11e8-9bb4-4137d4f6a053.png">

**Comment by chugginselifesciences** [comment]
@Maelplaine Do you know what menu items are needed here for IJM? Is it just Issues and Forthcoming? Will they have an about section?

**Comment by chugginselifesciences** [comment]
@Maelplaine Looking at the menu on the existing IJM journal...

![image](https://user-images.githubusercontent.com/41907215/48347739-05f15980-e677-11e8-886c-18565b1a915c.png)

... I feel we should provide a menu of links to:

- Research categories (same as eLIfe)
- Aims & Scope ("about")
- Editorial Board
- Submission Policy
- Notes for Authors
- Notes for Reviewers

The home page/main list would show latest issues and forthcoming articles. Primary Nav #24 could then include links to all issues and all forthcoming articles. Do you think these warrant their own page? Or is it sufficient to list all on the home page?

Alternatively we could provide a single "About" link in the primary navigation. Then within that page the above static pages are accessible via similar navigation bar as below:

![image](https://user-images.githubusercontent.com/41907215/48348129-50270a80-e678-11e8-875f-0d5b0ab8d675.png)

**Comment by Maelplaine** [comment]
Let's include the menu items below in the main menu (aka fly-out menu):
- Research categories
- Aims & Scope
- Editorial Board
- Submission Policy
- Notes for Authors
- Notes for Reviewers

**Comment by Maelplaine** [comment]
@chugginselifesciences We can go for the home page links only for the MVP. A 'Research categories' page could be added in a later release

**Comment by thewilkybarkid** [comment]
Closing this as it's no longer required. I assume it might reappear in the future.
