### ISSUE TITLE
Block robots on all Libero sites

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#164]
## Problem / Motivation
 
- WHO wants this?
- WHEN and WHERE do they want it?
- WHAT do they want?
- WHY do they want this?

## Proposed solution

- Is like this 
- And like this

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions

- A question
- An assumption

## Technical notes
- We could use this technology 
- More notes or suggestions

**Comment by giorgiosironi** [comment]
Sample implementation (more complex than needed here): https://github.com/elifesciences/journal-formula/blob/ca4f089ef9469672e7e010581b8e51eb12e43958/salt/journal/config/etc-nginx-traits.d-robots.conf

Nginx that are interesting for this, at least these two:
- https://github.com/libero/sample-configuration/blob/master/docker-compose.yml#L159
- https://github.com/libero/sample-configuration/blob/master/docker-compose.yml#L176

**Comment by giorgiosironi** [comment]
Specification is to block everything, everywhere.

**Comment by giorgiosironi** [comment]
@GiancarloFusiello has just been volunteered to do this.

**Comment by giorgiosironi** [comment]
Being rolled out now.

**Comment by giorgiosironi** [comment]
https://github.com/libero/sample-configuration/commit/884a696cac3cdadc6bc7db9712a40c45c877304c seems [deployed](https://travis-ci.com/libero/environments/builds) but http://unstable.libero.pub/robots.txt still a 404, investigating.

**Comment by giorgiosironi** [comment]
Ah, the `web` container nginx config change only adds it to http://unstable--dummy-api.libero.pub/robots.txt

**Comment by giorgiosironi** [comment]
All correct now:
```
http://unstable.libero.pub/robots.txt
http://unstable--api-gateway.libero.pub:8081/robots.txt
http://unstable--jats-ingester.libero.pub:8085/robots.txt
http://unstable--pattern-library.libero.pub/robots.txt
```
