### ISSUE TITLE
Add info bars

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#171]
See eLife.

Don't need to split markup and styling.

Blocks #169 (info bar on demo site).

- [x] Add pattern to pattern library (libero/pattern-library#115)
- [x] Implement in browser (libero/browser#92)
- [x] Add to the unstable environment (https://github.com/libero/sample-configuration/pull/68)

**Comment by davidcmoulton** [comment]
PRs:
https://github.com/libero/pattern-library/pull/115
https://github.com/libero/browser/pull/92

**Comment by thewilkybarkid** [comment]
@chugginselifesciences To clarify, is the info bar mean to be above or below the line? eLife has it above:

<img width="414" alt="Screenshot 2019-06-27 at 09 32 41" src="https://user-images.githubusercontent.com/1784740/60250531-baff1c00-98be-11e9-824d-0d487cb4ffc0.png">

But never been certain if that's right or not.

**Comment by chugginselifesciences** [comment]
@thewilkybarkid Below the line would be better if possible. Thanks.
