### ISSUE TITLE
Images in articles from JATS-Ingester using incorrect URL

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/libero#173]
On http://unstable.libero.pub images in ingested articles are not using the correct URL.

For http://unstable.libero.pub/articles/00666 this is an example of an img tag:
<img src="https://unstable-jats-ingester-expanded.s3.amazonaws.com/fig1-v1.jpg" alt="" class="image">
This results in the image not appearing on the page.

The `xml:base=` attribute added to the `jats:article` tag by the ingester is set to:
https://unstable-jats-ingester-expanded.s3.amazonaws.com/elife-666-vor-1

Therefore, the url used in the img tag should be:
`<img src="https://unstable-jats-ingester-expanded.s3.amazonaws.com/elife-666-vor-r1/fig1-v1.jpg" alt="" class="image">`

**Comment by thewilkybarkid** [comment]
Take a look at https://tools.ietf.org/html/rfc3986#section-5.2, specifically:

> return a string consisting of the reference's path component appended to all but the last segment of the base URI's path (i.e., excluding any characters after the right-most "/" in the base URI path, or excluding the entire base URI path if it does not contain any "/" characters).

You'll need a trailing slash if you want the `elife-666-vor-1` component included in the result.

**Comment by GiancarloFusiello** [comment]
> You'll need a trailing slash if you want the elife-666-vor-1 component included in the result.

Similar to a URL being entered into a browser, it's the job of the website (consumer) to be and to handle routes with and without a trailing slash. As the issue is on the consumer side, I would expect the content-store to be able to handle both the inclusion and exclusion of a trailing slash.

**Comment by thewilkybarkid** [comment]
XML Bass follows RFC 3986 for its URI resolution rules, so it is working correctly.

**Comment by giorgiosironi** [comment]
RFC 3986 seems clear, it behaves the same as [the HTML <base> element](https://jsfiddle.net/379na5jy/).

**Comment by GiancarloFusiello** [comment]
Thank you, @giorgiosironi. The jsfiddle you posted is very clear. I wasn't aware that this is the approach agreed upon that would be used.

Can someone point out in the RFC 3986 document where this is explained specifically? Unless my english is poor, this does not detail the requirement of a trailing slash:
>5.2.  Relative Resolution
>
>   This section describes an algorithm for converting a URI reference
>   that might be relative to a given base URI into the parsed components
>   of the reference's target.  The components can then be recomposed, as
>   described in Section 5.3, to form the target URI.  This algorithm
>   provides definitive results that can be used to test the output of
>   other implementations.  Applications may implement relative reference
>   resolution by using some other algorithm, provided that the results
>   match what would be given by this one.

Also, I would like to point out that the specification of the task for creating the jats-ingester, point 6 does not indicate the need for a trailing slash:
> 6. Add `xml:base=""` attribute to `jats:artcle` tag like so:
>```xml
><jats:article xml:base="https://unstable-elife-style-content-adapter->expanded.s3.amazonaws.com/<article-id>">
>```

Perhaps in future more oversight from the creators of the consuming service is required?
