### ISSUE TITLE
 update search base image from alpine to slim

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/libero#174]
Building the search container takes a long time. This is due to dependencies using C libraries needing to be compiled because binaries for Alpine linux are not available from PyPI. Using debian as the base image would result in not having to compile C libraries when building the container, which will speed up build times but also result in a larger image.

In my opinion, the convenience of quicker build times outweighs the benefits of having a smaller image as adoption/contributions could be affected.

**Comment by giorgiosironi** [comment]
In the end, the size increase was in the ballpark of going [from 150 MB to 220+ MB](https://github.com/libero/search/pull/21#issuecomment-501600636) so negligible.
