### ISSUE TITLE
Update Elasticsearch

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/libero#177]
Update Elasticsearch to version 7.

**Comment by giorgiosironi** [comment]
For reference, the [EOL dates for both versions are in 2020](https://www.elastic.co/support/eol), with `7.1` being farther into the future.

**Comment by giorgiosironi** [comment]
Approved https://github.com/libero/search/pull/23; the same change need to be done on [`sample-configuration`](https://github.com/libero/sample-configuration/blob/master/docker-compose.yml#L131).
