### ISSUE TITLE
Write Airflow logs to s3 bucket

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/libero#193]
When the jats-ingester is restarted or the local volume is full logs for past jobs can be lost.

**Task**
- configure jats-ingester dev environment with remote logging
- create s3 bucket `unstable-jats-ingester-logs`
- configure sample-configuration with remote logging for the jats-ingester

**Comment by giorgiosironi** [comment]
Depends on https://github.com/libero/libero/issues/192
