### ISSUE TITLE
reindex search after sending content to content-store

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/libero#201]
Currently to update the homepage with recently ingested content the search service needs to be called manually to reindex its content.

As a temporary measure to automate this, a task should be added to repopulate search with recently ingested content

**Task**
- add a task at the end of `process_elife_zip_dag` to that sends a `POST` request to `http://api-gateway:8081/search/populate`

**Comment by thewilkybarkid** [comment]
Works as the content store processing is (currently) blocking. Other option is a (very?) frequent cron job, but given everything is reindexed this approach probably better for now.
