### ISSUE TITLE
Coding standard automated checks for Python projects

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#35]
Coding standards common problems:

- mixture of formatting patterns (single and double quotes)
- enforcement of type hints
- unused variables, leftover unused imports

Standard tools for enforcing used at elife:
- [flake8](http://flake8.pycqa.org/en/latest/) for code style
- [autopep8](https://github.com/hhatto/autopep8) for reformatting code automatically
- [pylint](https://pylint.readthedocs.io/en/latest/) and [pyflakes](https://github.com/PyCQA/pyflakes) for static analysis
- [proofreader-python](https://github.com/elifesciences/proofreader-python) as an eLife-specific tool that wraps some of the above to ensure a consistent configuration

We may use some of these tools directly and find a way to extract a common configuration later.
/cc @thewilkybarkid for common proofreader-python problems

**Comment by de-code** [comment]
Just to be sure, we don't want to use proofreader-python for now?

**Comment by giorgiosironi** [comment]
It may be too eLife-specific and/or force too many pinned versions of dependencies. I'd welcome an experiment.

**Comment by de-code** [comment]
Also worth adding a markdown linter. The one used in VSCode is https://github.com/DavidAnson/markdownlint but requires an extra dependency. Perhaps use a separate docker image for that.

**Comment by de-code** [comment]
First PR to introduce pylint: https://github.com/libero/content-store/pull/9

**Comment by de-code** [comment]
I wasn't planning on adding `autopep8` as part of the pipeline. It's probably more useful for developers to make 'legacy' code compliant. Unless there are strong opinions.

**Comment by de-code** [comment]
Actually wondering whether we should split the ticket instead, I can create one for pylint (currently in checking), flake8.

Optionally:
* pyflakes (do we need it if we use pylint?)
* markdown linting

**Comment by de-code** [comment]
The scope of the ticket isn't well defined, can we now define it as please:

- [pylint](https://github.com/libero/content-store/pull/9)
- [flake8](https://github.com/libero/content-store/pull/14)
- [markdownlint](https://github.com/libero/content-store/pull/15)

It mention _Python projects_. I believe at the time of creation it was just the [content-store](https://github.com/libero/content-store). I think we should have separate tickets for each project (e.g. now validator?).

**Comment by giorgiosironi** [comment]
I'd stop with `content-store` and extract knowledge and tools from there after the setup is stable.

The current tools cover both style (`flake8`) and semantics (`pylint`) so I wouldn't add anything else at the moment unless you have something in the pipeline to try.

**Comment by de-code** [comment]
No, there was nothing else I was going to add.

Apart from [markdownlint](https://github.com/libero/content-store/pull/15) (if you consider markdown as code).

**Comment by giorgiosironi** [comment]
`markdownlint` approved and merged, it's useful to get feedback on minimal documentation changes. Let's consider it experimental if we have doubts about its stability.

**Comment by giorgiosironi** [comment]
Can probably be closed now?
