### ISSUE TITLE
Build content-validator

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#38]
To provide feedback on changes and pull requests, run:

- [ ] a Travis CI pipeline
- [ ] that runs at least a Python command (`pytest` better if it's there by the time this is picked up)
- [ ] a wheel-building process
- [ ] run the same checks with without the `Pipfile.lock` to canary-test dependencies

**Comment by gnott** [comment]
I have some ``pytest`` tests locally already. I'm undecided the functions I have are best though, I want to take a second look.

**Comment by gnott** [comment]
It might be best if this ticket remains open until there is a schema to define the ``front`` part. Then hopefully there are some schema files to use as fixtures, and I can adapt my validation tests over to it for a PR into master. Can coordinate with @thewilkybarkid about how the schemas will go together and if this is an end result of the schema building.

**Comment by giorgiosironi** [comment]
Agreed, removing from TODO column for now (remains in the Milestone).
