### ISSUE TITLE
‘Article and author information’ section and header author/affiliations list

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#5]
## Problem / Motivation
 
- WHO reader and author
- WHEN landing on an article page
- WHERE below the title
- WHY because the authors are considered significant to the quality of the paper and because people want to collaborate with the authors

## Proposed solution

- Authors/affiliations list in the headers
- Corresponding author’s email address is linked to: ‘Article and author information’ section contain the following info: pub history, copyright, funding, competing interest, affiliating list

## Tasks
- [ ] Define authors
- [ ] Define affiliations
- [ ] Define funding
- [ ] Define publication history
- [ ] Define copyright
- [ ] Display authors
- [ ] Display affiliations
- [ ] Display funding
- [ ] Display publication history
- [ ] Display copyright

## Assumptions
- Authors are optional.
- Order is important.
- More than 9 authors are hidden behind a ‘see more’ link, and all but 1 hidden on small screens (unless there’s 2 or fewer authors).
- Authors can be in (nested) groups.
- There can be co-first authors / contributed equally 

## Clarification needed
- What contact methods? Just email address?
> Just email for now, maybe twitter later and phone number
- Do groups have to contain people?
> eLife groups do not need to contain people
RSC & IJM don’t need groups
- Are ‘on behalf of’ entries supported? How do they work?
> They would still appear as an author
> eLife had it once and there is a JATS for that. Not critical for MVP
IJM don’t need that
- Do we need to do anything special with co-first authors?
> Current elife solution’s fine for now
IJM don’t need that
- Are we including ethics?
>	Yes
	IJM don’t need that
- Are we including acknowledgements?
>      Yes
IJM need that
- Are we including reviewing editors?
> eLife does it but not all of the journals do it
IJM don’t need that
- How should copyright work? Not all content has a copyright.
>	All IJM and eLife articles will have a copyright.
> RSC copyright not in the XLM, use the metadata
- How do we include the funding statement
> Ability to have "funding statements not associated with individual author" is important for Hindawi and RSC
> Downstream services such as WoS have different approaches to "extract funder information" with some coming from the article body

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/43398555-53bd03fe-9400-11e8-9a5b-35d3d0aa76f6.png)

**Comment by pmollahan** [comment]
Hi @Maelplaine 

There were some clarifications discussed relating to "funder" information. These included:

- Ability to have "funding statements not associated with individual author" is important for Hindawi and RSC
- Downstream services such as WoS have different approaches to "extract funder information" with some coming from the article body

**Comment by Maelplaine** [comment]
Thanks @pmollahan I have added this to the ticket description.

**Comment by Maelplaine** [comment]
@thewilkybarkid Is it possible to add any kind of sub-section in this ‘Article and author information’ section if it is in the XML? IJM will need a couple of new sub-sections such as Code Availability and Data Availability (see attached PDF)

[IJM-template.pdf](https://github.com/libero/libero/files/2822302/IJM-template.pdf)

**Comment by thewilkybarkid** [comment]
I think we should scale back the scope of this ticket (there's a _lot_ of metadata and possibilities). Author and affiliation names seem the most pressing.

Looking at JATS4R/DAR, could start with:

```xml
<article>
  <front>
    <article-meta>
      <contrib-group>
        <contrib contrib-type="author">
          <string-name>[name]</string-name>
          <xref ref-type="aff" rid="[id]">[anything]</xref>
          [..]
        </contrib>
        [..]
      </contrib-group>
      [..]
    </article-meta>
  </front>
</article>
```

and

```xml
<aff id="[id]">[name]</aff>
```

located anywhere(?).

**Comment by thewilkybarkid** [comment]
Speaking to @Melissa37, a simple `<aff>` inside the `<contrib>` should be the first step, so:

```xml
<article>
  <front>
    <article-meta>
      <contrib-group>
        <contrib contrib-type="author">
          <string-name>[name]</string-name>
          <aff>[name]</aff>
        </contrib>
        [..]
      </contrib-group>
      [..]
    </article-meta>
  </front>
</article>
```
