### ISSUE TITLE
Create homepage for Libero

### ISSUE THREAD

**Issue by BlueReZZ** [libero/libero#60]
## Problem / Motivation
 
- WHO publishers, developers and open infrastructure supporters
- WHEN on launch of the governance press release WHERE https://libero.pub 
- WHAT the current redirection to Github should be replaced with a nicely branded, content-rich homepage
- WHY  while we’re planning to build out a separate website to describe eLife’s technology and innovation profile in 2019, we would also like to introduce a landing page for Libero resources in association with the formation of a steering committee. The landing page should provide a single point of access for information on Libero – what it is, what it’s for and what’s going on – for anyone interested.

## Proposed solution

- A single webpage, with branding similar to the current goverance page at https://libero.pub/governance/ containing content as provided in this **(CURRENTLY PRIVATE)** google doc: https://docs.google.com/document/d/1mcgOyfO54c28RC-7FhA-2Q5gP3vIxXrNnqe6yB1pwsw

## Tasks

- [ ] Create page reflecting the content in the file above

## Clarification needed and assumptions

- The content is not yet complete or approved. 
- The document has limited access so needs to be moved/copied to the Libero Team Drive or shared appropriately

## User interface / Wireframes

TBC

**Comment by discodavey** [comment]
Started the build on this and placed the content that we have so far. Just to point out the content is not complete or signed off so may well be changed at some point.

**Comment by discodavey** [comment]
@thewilkybarkid Do we have official logos for Coko, Hindawi and Digirati? I have currently taken one's from their sites and ours for the time being.

**Comment by rowenamaskell** [comment]
Nearly* final copy is now here: https://docs.google.com/document/d/1G6e0TQ1MbMGy6LSssCHTcFvDiLeCuaXyPIjB4bNT-M0/edit#heading=h.pxtchup8mdtd
There are just a couple of points with questions, but otherwise it's set.

@discodavey I've added you so you should have access to the document.

**Comment by rowenamaskell** [comment]
![digirati logo](https://user-images.githubusercontent.com/40834282/48485965-1ee24200-e812-11e8-9ed2-1754122869cc.png)
![hindawi logo](https://user-images.githubusercontent.com/40834282/48485971-230e5f80-e812-11e8-908d-015741b44215.png)
![coko foundation logo](https://user-images.githubusercontent.com/40834282/48485978-26a1e680-e812-11e8-8f67-d0d48bc52a4d.png)

**Comment by discodavey** [comment]
https://github.com/libero/libero.github.io/pull/16

**Comment by rowenamaskell** [comment]
Emily's Press release for the governance doc will go out at 1pm on Wednesday 21st. Could we aim to publish this by 12.30 that day? Many thanks!

**Comment by rowenamaskell** [comment]
Dave kindly showed me the page yesterday and it's looking great! Are we likely to have the images ready today, ahead of going live with this page tomorrow?

Also, Dave I tried to share the link you'd sent me with Jen yesterday and it had expired I think. Can I have another once the images are in? Thanks!

**Comment by BlueReZZ** [comment]
I have the latest version of the site running on my machine and can supply the link when required.

**Comment by chugginselifesciences** [comment]
Hi all. Please see below for mockups at our large desktop, small desktop, tablet and mobile breakpoints. I've created an image with generic Libero mockups on white devices that I've intended to align with the central column of text. Instead of including the logo and "powered by eLife" into the image I will supply them as separate assets to avoid them scaling down with the image.
<br/>
**1200px +** 
![1200](https://user-images.githubusercontent.com/41907215/48782654-91ea2d80-ecd6-11e8-9825-dff2061e9a27.png)
**900px +**
![900](https://user-images.githubusercontent.com/41907215/48782659-944c8780-ecd6-11e8-8602-ecdf7a99bc52.png)
**730px +**
![730](https://user-images.githubusercontent.com/41907215/48782664-97477800-ecd6-11e8-8ce3-6fd6a1c8e06e.png)
**320px +**
![320](https://user-images.githubusercontent.com/41907215/48782672-9a426880-ecd6-11e8-8fca-715eea8476ba.png)

@discodavey I'll follow up in a moment with the assets.

**Comment by chugginselifesciences** [comment]
In this zip you should find the SVGs for the libero logo, "powered by eLife" and high res devices image.

Let me know if you need anything else. The libero logo should be used at 39px x 49px and "powered by eLife" at 66px x 49px. The image is exported at 2x.

[libero-homepage-assets.zip](https://github.com/libero/libero/files/2600384/libero-homepage-assets.zip)

**Comment by Maelplaine** [comment]
Thanks @chugginselifesciences it looks nice

**Comment by discodavey** [comment]
I think the logo's sit right where they. They just look like they are floating out of place and not sure they will go with the framework we have.

@BlueReZZ  What's your thoughts on this?

**Comment by chugginselifesciences** [comment]
@discodavey I based the logo placement on the far left and right edges of the grid and breakpoints we use for the journal. The image and text then based on the "eight-twelfths" class to provide the central column. If the Libero homepage behaves differently then maybe we'll have to change the logo placement.

**Comment by chugginselifesciences** [comment]
@discodavey please disregard above. For the sake of a short term fix I've included the logos into the image. It won't be responsive but we can sort that after afterwards.

![libero-devices-and-logos](https://user-images.githubusercontent.com/41907215/48788025-daf3af00-ece1-11e8-9601-d17525a13b3e.png)

**Comment by chugginselifesciences** [comment]
And the footer using the same SVG at 62px tall. 48px from the top of the footer and 48px above the centered footer text (if the text in this image is different please stick with what you've got). Thanks

![footer-elife](https://user-images.githubusercontent.com/41907215/48788489-d54a9900-ece2-11e8-9797-17fdfa039187.png)
