### ISSUE TITLE
Add a CONTRIBUTING.md to the community repo

### ISSUE THREAD

**Issue by BlueReZZ** [libero/libero#61]
## Problem / Motivation
 
- WHO existing and potential contributors
- WHEN and WHERE in a `CONTRIBUTING.md` file in https://github.com/libero/community/
- WHAT contribution information
- WHY so people can learn how to make contributions without having to ask 

## Proposed solution

- Add a `CONTRIBUTING.md` file as per the recommendations on Github etc.
- Link to the CLA and help 

## Tasks

- [x] Create `CONTRIBUTING.md` in `libero/community` as per Github guidelines

**Comment by discodavey** [comment]
https://github.com/libero/libero/pull/67

**Comment by discodavey** [comment]
Paused this for the moment until we get content (As per comments by Chris in the PR) and will remove link from Governance page until this ticket is complete.

**Comment by BlueReZZ** [comment]
Completed with https://github.com/libero/community/pull/19
