### ISSUE TITLE
Display publication date

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#7]
## Problem / Motivation
 
- WHO reader, publisher
- WHEN landing on an article page
- WHERE article header, below the authors
- WHY so people know it’s still relevant or new

## Assumptions
- Current format is suitable for all the journals: Jul 24, 2018
- Localization format is Jul 24, 2018 but we should allow for other locales
- The default time and timezone is 00:00:00UTC

## Clarification needed
- Does the source of truth for the date comes from the XML content, not from the moment in which the - article is really published in the article store? Can both work?
> Yes but it would need a validation to make sure the dates match
Assuming that there is no versioning of article and assuming that the timezone of the publisher and system match
- Can these include time? And timezone?
> No it doesn't (eLife, Hindawi, RSC)
- What dates do we need? eLife uses 3 (publication date, status date, version date)
> For IJM use the date when published in the forthcoming article section
> RSC displays the 'article received' date, 'accepted' date and 'first published' date
> Hindawi: Submitted, Revised, Accepted, Published
- Are these Lax dates? publication date, status date, version date
> TECH TEAM?

## Technical notes
- Dates should be stored as timestamps (relevant database types)
- Display should take (one of the) journal’s defined locale(s), not user’s.
- Should be stored in UTC, and timezone (if required) stored separately

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/43400757-730a20ce-9406-11e8-861f-33a5176b92b0.png)

**Comment by thewilkybarkid** [comment]
Looking at JATS4R, maybe should use the first matching:

```xml
<pub-date date-type="original-publication" iso-8601-date="[something]">
    [anything]
</pub-date>
```

**Comment by thewilkybarkid** [comment]
The above is now uncertain, as it sounds like JATS4R's recommendation is going to change. /cc @Melissa37

**Comment by Melissa37** [comment]
Yes, I don't think we have time to wait for the JATS4R recommendation on versioning to be finalised - could take months and months.
I would stick with something PubMedCentral recommends, for now.

**Comment by thewilkybarkid** [comment]
Having read the PMC guidance and JATS docs, going to suggest `<pub-date date-type="pub" iso-8601-date="[something]">`. Though I'm not sure how common `@iso-8601-date` is here, so might have to pick out `<year>`, `<month>` and `<day>` too.

**Comment by discodavey** [comment]
The date is now to be all uppercase. Decision made to do this mid March 2019

**Comment by thewilkybarkid** [comment]
Going to implement `<pub-date date-type="pub" iso-8601-date="[YYYY-MM-DD]">`, otherwise use `<day>[DD]</day><month>[MM]</month><year>[YYYY]</year>` (and skip if it still doesn't match, so partial dates etc aren't supported).

**Comment by thewilkybarkid** [comment]
Pattern library: https://github.com/libero/pattern-library/pull/75
Browser: https://github.com/libero/browser/pull/66
