### ISSUE TITLE
Publish pattern library config generation to npm

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#81]
## Problem / Motivation
 
- WHO wants this? developers
- WHEN and WHERE do they want it? before they build any patterns
- WHAT do they want? pattern library config generator published to npm
- WHY do they want this? to make it easier to develop patterns using Libero

**Comment by giorgiosironi** [comment]
https://docs.travis-ci.com/user/deployment/npm/ should be helpful.
Do we mean this to be a separate repository from `patterns-core`?
Do we have already a NPM account for `libero` or should it be created?

**Comment by thewilkybarkid** [comment]
`patterns-core` should really be renamed `pattern-library`.

Not sure of the best home for the `export` library, might be multiple places. Other pattern libraries (eg eLife) probably want to use NPM. Other uses (eg getting it into Browser) could use NPM, but availability through Composer is probably simpler (could be a Git repo, a TAR/ZIP etc, see https://getcomposer.org/doc/05-repositories.md#types).

**Comment by davidcmoulton** [comment]
@giorgiosironi Thanks, that's useful. Yes, I guess the config generation should be a separate repository as we're intending to publish it to npm as a package.  I'm not aware of a `libero` account on npm.

@thewilkybarkid agreed re the rename, I'll do this.

**Comment by davidcmoulton** [comment]
Stand alone repo for the config management is at https://github.com/libero/libero-pattern-library-config-manager (verbose name, taking suggestions).

**Comment by davidcmoulton** [comment]
@giorgiosironi Looking to publish https://github.com/libero/libero/issues/86 on npm, might make sense to set up a Libero organisation on npm for this. Meagre details at https://www.npmjs.com/features. What do you think?

**Comment by giorgiosironi** [comment]
(private) accounts at https://github.com/elifesciences/it-admin/blob/master/libero.md

**Comment by giorgiosironi** [comment]
`liberoadmin` is now the only `Owner` user, that must be accessible to add new users (but not to authorize existing users on packages, for which `Admin` suffices).

**Comment by davidcmoulton** [comment]
Package published as `@libero/pattern-library-config-manager`: https://www.npmjs.com/package/@libero/pattern-library-config-manager
