### ISSUE TITLE
Generate CSS custom properties

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#86]
## Problem / Motivation
 
- WHO wants this? Developers working on the front end
- WHEN and WHERE do they want it? In the pattern library codebase
- WHAT do they want? CSS custom properties
- WHY do they want this? Modern good practice; more flexibility in CSS architecture.

## Proposed solution

- Use CSS custom properties to define in the browser some of the properties currently only specified as sass variables
- Implement with sass variable fallbacks at compile time where possible

## Clarification needed and assumptions

- Some css architecture patterns don't allow for straightforward fallbacks with sass variables due to the nature of CSS custom properties being evaluated in the browser at run time. Things should still be usable when CSS custom properties are not supported in the browser

## Technical notes
- Don't implement it in a way that would make it much harder to extend the sass codebase

**Comment by davidcmoulton** [comment]
PR: https://github.com/libero/libero-pattern-library-config-manager/pull/2

**Comment by thewilkybarkid** [comment]
Bit difficult to try out due to the divergence between the two copies (eg px handling).

Next task I think is to work out _how_ to use custom properties. Might be worth adding some manually to the Libero PL (ie using the generated variable as its value) to try it out.
