### ISSUE TITLE
Investigate using CLDR with CSS generated content

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#89]
## Problem / Motivation
Currently CSS generated content is not localised (e.g. the comma separators between list items in some lists), but specified directly as `content: ', ';`. Although this is fine for (most?) left-to-right languages, it's not appropriate for most right-to-left languages.

## Proposed solution
Use [CLDR](http://cldr.unicode.org) to supply the correct locale-aware content for CSS generated content. Will need to investigate the best source of CLDR data to use for this.

**Comment by thewilkybarkid** [comment]
List data is available in https://www.npmjs.com/package/cldr-misc-full (eg https://github.com/unicode-cldr/cldr-misc-full/blob/aa258a9eecf2669660164d414ce7e3165967d299/main/en/listPatterns.json#L14).

Alternatively could look at something like https://www.npmjs.com/package/cldr.

**Comment by thewilkybarkid** [comment]
https://github.com/libero/pattern-library/pull/45
