### ISSUE TITLE
Article classification specific to a journal field

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#9]
## Problem / Motivation
- WHO librarian? Citation database provider?
- WHEN & WHERE in the article page but probably in downstream deliveries as well
- WHAT a industry-specific keyword group
- WHY to provide search filters and listings both inside the journal and from external databases

## Proposed solution
Provide a list of keywords, organized in group, in the footer of the article page. The keywords don’t link to anything else yet.

## Tasks

- [ ] Article schema must accept some keyword groups and some items in those groups
- [ ] Journal renders keyword groups on the article page

## Clarification needed and assumptions
Is this a keyword group that is different from other keyword groups like research organisms, categories and tags? Or is it a different instance of the same pattern?

## Technical notes
- IJM is using the JEL classification which is used on article in economics journals
https://en.wikipedia.org/wiki/JEL_classification_codes
- The typesetter classifies this as no different than a keyword group provided by the author:
https://github.com/microsimulation/ijm-xml/blob/master/ijm-00666.xml#L2273-L2281
- It may be styled or treated differently thanks to its kwd-group-type.

## User interface / Wireframes
Not identical but could be similar to:
![image](https://user-images.githubusercontent.com/39725642/43401505-3c9f6164-9408-11e8-9043-5b9842893880.png)

IJM JEL tafs
![image](https://user-images.githubusercontent.com/39725642/43402920-b2a2be30-940b-11e8-99c4-326a04784594.png)

**Comment by thewilkybarkid** [comment]
Don't think there's anything to do here, it's already supported.

But:

> It may be styled or treated differently thanks to its kwd-group-type.

Not sure what this means.

**Comment by Maelplaine** [comment]
@thewilkybarkid 
Yes that makes sense it will be included in the XML

> Not sure what this means.
That's the XML tag for the article classification name. For example, "Research Organism" for eLife or JEL Classification for IJM

**Comment by thewilkybarkid** [comment]
> That's the XML tag for the article classification name. For example, "Research Organism" for eLife or JEL Classification for IJM

`@kwd-group-type` is an attribute (ie for machines). [We've implemented using the `<title>` element (which contains a human-readable form) or certain `@kwd-group-type` values (currently `author-keywords` and `research-organism`).](https://github.com/libero/jats-support/blob/84a3d3e81731ef5d31aaed01e66938730788674c/src/support.sch#L99-L113)

If there's an expectation about being 'styled or treated differently', that needs clarifying/specifying.

/cc @Melissa37

**Comment by Melissa37** [comment]
For a MVP I don't think we need to try and link this to the taxonomy or anything for machine reading purposes. IJM has had them hidden in PDFs so far and if they want to invest in this additional piece then that's something for development by them.

Does that answer the question?

Unless you are asking whether they need a separate section with a header? I think not, again for MVP.

Hope I understand!
M

**Comment by thewilkybarkid** [comment]
Yep, I read this as there's nothing to do so can close. (IJM can already include their 'JEL classification' as long as they include a `<title>`.)
