### ISSUE TITLE
Replace pattern library's local config management with npm module equivalent

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#90]
## Problem / Motivation
Pattern library is using an out of date approach to configuration management.

## Proposed solution
Replace the explicit configuration management approach with the newer approach from the npm module `@libero/pattern-library-config-manager`, taking care to port over any config values from the pattern library into the module at the same time, to prevent regression.

Note that the `_in_px` string handling in the pattern library config management should also be ported over to the npm module at the same time, as this will still be required, and was introduced into the pattern library after the config manager module was split off from it.

### swap over the config handling

- [x] install the npm module as a dependency of the pattern library with `npm install @libero/pattern-library-config-manager --save`
- [x] port over the config values from pattern library -> module
- [x] update the module's `ConfigDistributor` with the `_in_px` string handling from the pattern library
- [x] Update module's output paths to match current pattern library requirement
- [x] Delete `libero-config` directory from https://github.com/libero/pattern-library

### use the new values in sass

Sass maps have replaced sass variables. Mixins must be built to use these maps as necessary, replacing the bare use of sass variables. Note that merging will break the build until all direct references to Sass variables are replaced with using either the new mixins (see below) or the sass maps.
- [ ] build mixins and their tests to use the sass map properties
- [ ] replace sass variable usage with these mixins where possible, only using direct access to the sass maps when absolutely necessary

## Technical notes
- This should be expedited as the more Sass code written before this is merged in, the more code will need to be changed.

**Comment by davidcmoulton** [comment]
PR: https://github.com/libero/pattern-library/pull/42

**Comment by thewilkybarkid** [comment]
Closing this ticket as stale. Can create a follow up.
