### ISSUE TITLE
Add search to the unstable environment

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#96]
- [x] Publish a Docker image
    * [x] nginx and WSGI
    * [x] smoke test
    * [x] healthcheck
    * [x] signals
- [x] Deploy the image
- [x] Add an Nginx to act as an API gateway

Depends on #94, #108 and #109.

**Comment by giorgiosironi** [comment]
Added `DOCKER_*` and `TRAVIS_*` (future use) environment variables to settings.

**Comment by giorgiosironi** [comment]
On the deployment side the various PRs backlinked here are ready for review, with https://github.com/libero/sample-configuration/pull/20 being the only non-trivial one.

**Comment by giorgiosironi** [comment]
Currently open pull requests deal with all the remaining checklist items.

**Comment by giorgiosironi** [comment]
Deployed:
```
ubuntu@ip-172-31-70-78:~$ curl -sS -H 'Host: unstable--api-gateway.libero.pub' http://localhost:8081/search/ping
pong
```
but the EC2 instance is being throttled due to lack of CPU credits. Also want to open port 8081 for the `api-gateway` so that it is accessible from outside the instance.

**Comment by giorgiosironi** [comment]
Started in the last days:
![Screenshot_2019-03-15 Instances EC2 Management Console](https://user-images.githubusercontent.com/160299/54425330-f9f0d380-470c-11e9-8763-4117867c8c64.png)

**Comment by giorgiosironi** [comment]
We are at a baseline of CPU utilization of 20% now.

**Comment by giorgiosironi** [comment]
http://unstable.libero.pub:8081/search/ping is available now.

**Comment by giorgiosironi** [comment]
Only https://github.com/libero/search/pull/13 remains.

**Comment by giorgiosironi** [comment]
Using that healthcheck in https://github.com/libero/sample-configuration/pull/23
