### ISSUE TITLE
Add list of teasers to the homepage

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#97]
Create a teaser to display a content title, suitable to display within in a teaser list.

- [x] Create teaser pattern
- [x] Create teaser list pattern
- [x] Add to homepage
  - [x] Fetch search results
  - [x] Fetch content items
  - [x] Display teaser list
- [x] Deployed in the `unstable` environment

Depends on #93 and #98.

**Comment by nlisgo** [comment]
It's tempting to introduce links to headings but we could take that on as a separate feature and add in `italic`, `sub` and `sub`.

**Comment by nlisgo** [comment]
> It's tempting to introduce links to headings but we could take that on as a separate feature and add in `italic`, `sub` and `sup`.

`italic`, `sub` and `sup` are already supported

**Comment by thewilkybarkid** [comment]
Deployment in https://github.com/libero/sample-configuration/pull/27.
