### ISSUE TITLE
Add homepage to Browser

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#98]
Add a homepage containing a content header with the site name.

<img width="1395" alt="Screenshot 2019-03-19 at 10 22 21" src="https://user-images.githubusercontent.com/1784740/54600738-5c134680-4a35-11e9-9086-b8e08d712b74.png">

(Image will come later.)

**Comment by thewilkybarkid** [comment]
https://github.com/libero/browser/pull/52

**Comment by thewilkybarkid** [comment]
Final task: https://github.com/libero/sample-configuration/pull/25

**Comment by BlueReZZ** [comment]
We need some clarification from @Maelplaine or @chugginselifesciences on what the demonstration journal's name is going to be. I've discussed with some people that we need it to definitely not sound like a potentially real journal so `The International Journal of Publishing Innovation` sounds a bit too real (as detailed in the ticket screenshot). In https://github.com/libero/sample-configuration/pull/25 we've gone with `The International Journal for Demonstration` as that matches https://libero.pub

**Comment by chugginselifesciences** [comment]
@BlueReZZ to be honest I'd been going off your recommendation so far, so not thought about it myself until now. But I agree it potentially sounds too "real" as `The International Journal of Publishing Innovation`.

I'd be happy to go with `The International Journal for Demonstration` and it's a quick fix in the InVision link. But perhaps we should make it event clearer and go for something like `The Libero Demonstration Journal`. Or is that too dull or unofficial?

I think this ties into the work going into the libero.pub designs and will, I assume, play a part in face-to-face and online demos. Maybe it'll be demonstrated in talks or conferences by tech team members too?

So if the question is **_"What do we call the MVP journal used to demo and sell Libero"_** I think it's a decision for @gmaciocci and/or @BlueReZZ? 

It's easy enough to update and I think only appears on the homepage as we're using the Libero logo.

![image](https://user-images.githubusercontent.com/41907215/55321102-bf0ecf80-5470-11e9-900a-6c67fd50fcf9.png)
