### ISSUE TITLE
Create the article grid

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#99]
We have the first pattern that requires the grid to be used (https://github.com/libero/pattern-library/pull/38).

- [ ] Create single column grid (libero/pattern-library#54)
- [ ] Create 3 column grid (libero/pattern-library#54)
- [ ] Implement single column grid in Browser (https://github.com/libero/browser/pull/47)
- [ ] Implement 3 column grid in Browser (https://github.com/libero/browser/pull/47)

**Comment by davidcmoulton** [comment]
Related: some grid experiments. Consider disposable, but posting here in case it might be of use for reference.

**Comment by davidcmoulton** [comment]
I've got the eLife top level page grid implemented in CSS grid layout at https://davidcmoulton.github.io/dashboard-grid-tests/src/journal/article.html. Not final, but I think this does the job:
- Holds the content in a centred 12 column grid with a proportional width grid gap
- Allows a variable page 'margin' depending on the viewport width
- Imposes a maximum width on the central 12 columns above a max width
- Allows grid items to appear to break out of the grid, pulling to the left edge, the right edge or both edges
- Allows a keyline beneath a grid item to appear to break out of the grid while the grid item itself remains on grid (requires a wrapper element).

Notes:
- the grid gap is currently specified as a % value, but we could support other means of expression (in fact it would probably be an easier than this implementation using percent).

**Comment by davidcmoulton** [comment]
PR in progress: https://github.com/libero/pattern-library/pull/54/files
